### ISSUE TITLE
Sacar vista de Donate

### ISSUE THREAD

**Issue by loorely** [GirlsCodePy/girls-code-web#12]
No debe ser una vista separada

**Comment by elianaferreira** [comment]
Ya está el cambio, como es mínimo voy a mandar con el PR del [Issue14](https://github.com/GirlsCodePy/girls-code-web/issues/14). Una vez que se tenga ese cambio va a ser necesario hacer `npm run build` de manera a limpiar el caché y que no lance error al intentar entrar a `/donate` sino que muestre la pantalla de 404.
