### ISSUE TITLE
Componente para Quienes Somos en el index

### ISSUE THREAD

**Issue by loorely** [GirlsCodePy/girls-code-web#13]
Estilos y componentes agregados a la sección de Index 
Texto editable desde el CMS Netlify 
Link de equipo. 
Utilizar estilos del figma, pero los textos deben ser en base al invision: 

![image](https://user-images.githubusercontent.com/740232/79692092-415f6280-8231-11ea-82cf-1f5ebab32efe.png)

**Comment by bsandoval** [comment]
Closed by #18
