### ISSUE TITLE
Revision de estilos genericos en all.sass

### ISSUE THREAD

**Issue by loorely** [GirlsCodePy/girls-code-web#19]
Mudar todos los estilos al all.sass
Controlar tamaños de letras
Controlar colores

**Comment by loorely** [comment]
@grdnrt podrias darnos una mano con este? es darle amor al .sass

**Comment by grdnrt** [comment]
Uhhh si! Will do! @loorely

**Comment by grdnrt** [comment]
Do we want to implement some naming convention like [BEM](http://getbem.com/introduction/) and the like? cc @loorely @javierpf 

That aside, I think something like this will do the trick:

```
stylesheets
├── components
├── base
├── layout
├── .gitignore
├── public
│   ├── favicon.ico
│   ├── index.html
│   └── manifest.json
...
```

**Comment by javierpf** [comment]
Bien @grdnrt 
Yo creo que estaria super bien. Incluyo a @bsandoval, aunque pienso que seria una buena mejora!

**Comment by bsandoval** [comment]
Por mi también! Adelante

**Comment by grdnrt** [comment]
Super, avanzo con eso. Gracias chicos!
