### ISSUE TITLE
Componente de Actividades - Talleres

### ISSUE THREAD

**Issue by loorely** [GirlsCodePy/girls-code-web#29]
Incluir título para la página. Agregar nueva página en /activities
Los textos deben ser editables via netlify cms 
![image](https://user-images.githubusercontent.com/740232/80321619-78fb7b00-87ec-11ea-8b03-85f24e36aefc.png)

**Comment by gonzachr** [comment]
Hola! Puedo agarrar esta vista? ✋

**Comment by loorely** [comment]
Ya esta!

**Comment by gonzachr** [comment]
Bump!!

**Comment by gonzachr** [comment]
Seguimos avanzando?

**Comment by bsandoval** [comment]
@zant gonza, ahora retomamos!! que tal estas para continuar con este issue?

**Comment by zant** [comment]
Sii! Este finde tengo libra para continuar 👌
