### ISSUE TITLE
Integración con fotos en sección de teams

### ISSUE THREAD

**Issue by loorely** [GirlsCodePy/girls-code-web#76]
Agregar las fotos de las integrantes. 
Los cargos son: 

Presidenta: ​Gabriela Gaona
Vicepresidente: Liliana Estigarribia ​
Directora Secretaria: Melissa Bogado
Directora Financiera: Vanessa Cañete
Síndico Titular: ​Yasmin De Moraes

Las demás son Socias Colaboradoras 

Las imagenes se van a subir a esta carpeta: https://drive.google.com/drive/u/0/folders/0B4zpwt0wdzfiRzRDSEp2ZmRsUnM?resourcekey=0-zjsaS5CQ7L8TYebb6uBwcA

**Comment by ssruiz** [comment]
Completado en https://github.com/GirlsCodePy/girls-code-web/pull/107
