### ISSUE TITLE
Cambios de Textos 

### ISSUE THREAD

**Issue by loorely** [GirlsCodePy/girls-code-web#77]
la frase con la que estamos trabajando con temas de comunicación es con la frase "Ellas crean si creemos en ellas", que es la usamos desde Tigo Conecta.

Se puede unificar eso xfa. En la pestaña de la web, y en la página de inicio igual. Si se puede poner el hashtag al pie de la web estaría genial, así vemos desde dónde llega la gente usando el hashtag.

![Captura_de_Pantalla_2021-06-21_a_la_s__17_17_40](https://user-images.githubusercontent.com/740232/122841382-c167d900-d2c9-11eb-9731-3cdf554b5b59.png)

![Captura_de_Pantalla_2021-06-21_a_la_s__17_20_57](https://user-images.githubusercontent.com/740232/122841295-bca32500-d2c9-11eb-8f01-1768eea90772.png)
![Captura_de_Pantalla_2021-06-21_a_la_s__17_17_42](https://user-images.githubusercontent.com/740232/122841327-be6ce880-d2c9-11eb-985f-75b8ff896fb7.png)

**Comment by nahu** [comment]
Versión en inglés? y en el inicio, qué parte es coloreada en blanco (es/en)
